// Generated by CoffeeScript 1.6.3
(function() {
  Server.registerSpider({
    interval: 5,
    name: 'GooglePlus',
    displayName: 'Google+',
    type: 'sns',
    host: 'plus.google.com',
    needAuth: true
  });

  Server.on('Spider.runGooglePlus', function() {
    console.log('Run G+');
    return Server.emit('Spider.success', 'GooglePlus');
  });

}).call(this);

/*
//@ sourceMappingURL=googleplus.map
*/
