// Generated by CoffeeScript 1.6.3
(function() {
  var request;

  request = require('request');

  Server.registerSpider({
    interval: 100,
    name: 'MoegirlWiki',
    displayName: '萌娘百科',
    type: 'website',
    host: 'zh.moegirl.org',
    needAuth: false
  });

  Server.on('Spider.runMoegirlWiki', function() {
    return wait.launchFiber(function() {
      var apcontinue, e, page, req, _i, _len, _ref;
      apcontinue = '';
      try {
        while (true) {
          req = wait["for"](request, {
            url: 'http://zh.moegirl.org/api.php?action=query&list=allpages&apnamespace=0',
            qs: {
              aplimit: 500,
              apfrom: '一',
              format: 'json',
              apcontinue: apcontinue
            },
            json: true
          });
          _ref = req.body.query.allpages;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            page = _ref[_i];
            Server.emit('Spider.newItem', 'MoegirlWiki', page.title, 'title', 1);
          }
          if (req.body['query-continue'] == null) {
            break;
          }
          apcontinue = req.body['query-continue'].allpages.apcontinue;
        }
        return Server.emit('Spider.success', 'MoegirlWiki');
      } catch (_error) {
        e = _error;
        return Server.emit('Spider.error', e, 'MoegirlWiki');
      }
    });
  });

}).call(this);

/*
//@ sourceMappingURL=moegirlwiki.map
*/
