// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, google_plus, http, path, request, routes, user;

  express = require("express");

  routes = require("./routes");

  user = require("./routes/user");

  google_plus = require("./routes/google_plus");

  http = require("http");

  path = require("path");

  app = express();

  app.set("port", process.env.PORT || 3000);

  app.set("views", __dirname + "/views");

  app.set("view engine", "jade");

  app.use(express.favicon());

  app.use(express.logger("dev"));

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  app.use(app.router);

  app.use(require("less-middleware")({
    src: __dirname + "/public"
  }));

  app.use(express["static"](path.join(__dirname, "public")));

  if ("development" === app.get("env")) {
    app.use(express.errorHandler());
  }

  app.get("/", routes.index);

  app.get("/users", user.list);

  app.get("/google_plus", google_plus.list);

  http.createServer(app).listen(app.get("port"), function() {
    return console.log("Express server listening on port " + app.get("port"));
  });

  request = require('request');

  global.start_google_plus = function(token_type, access_token) {
    console.log(token_type, access_token);
    return request({
      url: "https://www.googleapis.com/plus/v1/people/me/people/visible",
      header: {
        authorization: "" + token_type + " " + access_token,
        origin: "http://localhost:3000"
      }
    }, function(err, body) {
      return console.log(body);
    });
  };

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
