// Generated by CoffeeScript 1.6.3
(function() {
  var analyzer, exporter_google, exporter_sogou, spider_moegirlwiki, transcoder_pinyin;

  spider_moegirlwiki = require('./lib/spider_moegirlwiki');

  analyzer = require('./lib/analyzer');

  transcoder_pinyin = require('./lib/transcoder_pinyin');

  exporter_sogou = require('./lib/exporter_sogou');

  exporter_google = require('./lib/exporter_google');

  exporter_google.start();

  setImmediate(function() {
    return spider_moegirlwiki.start(function(from, text, type, weight) {
      if (weight == null) {
        weight = 1;
      }
      return analyzer.analyze(null, text, type, weight, function(new_words, updated_words) {
        new_words.forEach(function(word) {
          return word.inputcode_pinyin = transcoder_pinyin.transcode(word.word);
        });
        return exporter_google.update(new_words, updated_words);
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
