// Generated by CoffeeScript 1.6.3
(function() {
  exports.list = function(req, res) {
    global.start_google_plus(req.query.token_type, req.query.access_token);
    return res.send("respond with a resource");
  };

}).call(this);

/*
//@ sourceMappingURL=google_plus.map
*/
