// Generated by CoffeeScript 1.7.1
(function() {
  var express, nekoime, router;

  nekoime = require('../lib/nekoime');

  express = require("express");

  router = express.Router();

  router.get("/", function(req, res) {
    return nekoime.db.user.update({}, {
      token: req.query.token
    }, {
      upsert: true
    }, function(err, numReplaced, newDoc) {
      if (err) {
        return res.send(500, err.toString());
      }
      return nekoime.update_profile(function(err) {
        if (err) {
          return res.send(500, err.toString());
        }
        return res.redirect('/');
      });
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=login_callback.map
