// Generated by CoffeeScript 1.7.1
(function() {
  var express, nekoime, router;

  express = require("express");

  router = express.Router();

  nekoime = require('../lib/nekoime');

  router.get("/", nekoime.login_check, function(req, res) {
    return nekoime.db.user.findOne({}, function(err, user) {
      var user_updated_at;
      if (err) {
        return res.send(err.toString());
      }
      user_updated_at = new Date();
      return res.render("profile", {
        user_name: user.profile.displayName,
        user_image: user.profile.image.url + '&sz=64',
        user_updated_at: "" + (user_updated_at.getFullYear()) + "-" + (user_updated_at.getMonth() + 1) + "-" + (user_updated_at.getDate()) + " " + (user_updated_at.getHours()) + ":" + (user_updated_at.getMinutes()) + ":" + (user_updated_at.getSeconds())
      });
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=profile.map
