// Generated by CoffeeScript 1.6.3
(function() {
  var fs, spawn, words;

  fs = require('fs');

  spawn = require('child_process').spawn;

  Server.registerExporter({
    name: 'SunPinyin',
    platform: ['Linux'],
    transcoder: 'pinyin'
  });

  words = [];

  this.start = function() {
    return setInterval(this.do_update, 3600);
  };

  this.update = function(new_words) {
    return words = words.concat(new_words);
  };

  this.do_update = function() {
    var result, word;
    if (!words.length) {
      return;
    }
    result = ((function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = words.length; _i < _len; _i++) {
        word = words[_i];
        _results.push("" + word.word + "\t" + word.weight + "\t" + (word.inputcode_pinyin.join(' ')) + "\n");
      }
      return _results;
    })()).join('');
    words = [];
    return fs.appendFile('result.dic', result, function() {
      var iconv;
      iconv = spawn('iconv', ['-f', 'utf-8', '-t', 'gb18030', '-o', 'result_gb18030.dic', 'result.dic']);
      return iconv.on('close', function(code) {
        var kill_ibus;
        if (code !== 0) {
          return console.log('iconv process exited with code ' + code);
        } else {
          fs.unlink('result.dic', function() {});
          kill_ibus = spawn('killall', ['ibus-daemon']);
          return kill_ibus.on('close', function(code) {
            var importer;
            importer = spawn('lib/sunpinyin_importer/import_google_userdict.py', ['result_gb18030.dic']);
            importer.stdout.on('data', function(data) {
              return console.log('stdout: ' + data);
            });
            importer.stderr.on('data', function(data) {
              return console.log('stderr: ' + data);
            });
            return importer.on('close', function(code) {
              if (code !== 0) {
                console.log('importer process exited with code ' + code);
              }
              spawn('ibus-daemon', ['-d']);
              fs.unlink('result_gb18030.dic');
              return console.log('exported');
            });
          });
        }
      });
    });
  };

}).call(this);

/*
//@ sourceMappingURL=Lsunpinyin.map
*/
