// Generated by CoffeeScript 1.6.3
(function() {
  var ffi, fs;

  fs = require('fs');

  ffi = require('ffi');

  this.start = function() {
    return fs.exists('result.dic', function(exists) {
      if (!exists) {
        return fs.writeFile('result.dic', '\xEF\xBB\xBF', {
          encoding: 'ascii'
        });
      }
    });
  };

  this.update = function(new_words, updated_words) {
    var result, word;
    result = ((function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = new_words.length; _i < _len; _i++) {
        word = new_words[_i];
        _results.push("" + word.word + "\t" + word.weight + "\t" + (word.inputcode_pinyin.join(' ')) + "\n");
      }
      return _results;
    })()).join('');
    return fs.appendFile('result.dic', result);
  };

}).call(this);

/*
//@ sourceMappingURL=Wgoogle.map
*/
