// Generated by CoffeeScript 1.6.3
(function() {
  Server.on('Analyzer.run', function(source, text, type, weight) {});

  this.analyze = function(db, text, type, weight, callback) {
    return callback([
      {
        word: text.replace(/[`~!@#$^&*()=|{}':;',\[\].<>/?~！@#￥……&*（）&;|{}【】‘；：”“'。，、？]/g, ''),
        weight: weight
      }
    ], []);
  };

}).call(this);

/*
//@ sourceMappingURL=analyzer.map
*/
