// Generated by CoffeeScript 1.6.3
(function() {
  var fs;

  fs = require('fs');

  this.update = function(new_words, updated_words) {
    var pinyin, result, word, _i, _j, _len, _len1, _ref;
    result = "";
    for (_i = 0, _len = new_words.length; _i < _len; _i++) {
      word = new_words[_i];
      _ref = word.inputcode_pinyin;
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        pinyin = _ref[_j];
        result += "\'" + pinyin;
      }
      result += ' ' + word.word + "\n";
    }
    new_words.join('\'');
    return fs.appendFile('搜狗词库.txt', result);
  };

}).call(this);

/*
//@ sourceMappingURL=exporter_sogou.map
*/
