// Generated by CoffeeScript 1.6.3
(function() {
  var request;

  request = require('request');

  this.start = function(callback) {
    return request({
      url: 'http://zh.moegirl.org/api.php?action=query&list=allpages&apnamespace=0&aplimit=500&apfrom=一&format=json',
      json: true
    }, function(error, response, body) {
      var page, _i, _len, _ref, _results;
      if (error) {
        throw error;
      }
      _ref = body.query.allpages;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        page = _ref[_i];
        _results.push(callback('moegirlwiki', page.title, 'title', 1));
      }
      return _results;
    });
  };

}).call(this);

/*
//@ sourceMappingURL=spider_moegirlwiki.map
*/
