// Generated by CoffeeScript 1.6.3
(function() {
  var fetch, request;

  request = require('request');

  fetch = function(callback, apcontinue) {
    if (apcontinue == null) {
      apcontinue = '';
    }
    return request({
      url: "http://zh.moegirl.org/api.php?action=query&list=allpages&apnamespace=0&aplimit=500&apfrom=一&format=json&apcontinue=" + apcontinue,
      json: true
    }, function(error, response, body) {
      var page, _i, _len, _ref;
      if (error) {
        throw error;
      }
      _ref = body.query.allpages;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        page = _ref[_i];
        callback('moegirlwiki', page.title, 'title', 1);
      }
      return fetch(callback, body['query-continue'].allpages.apcontinue);
    });
  };

  this.start = function(callback, apcontinue) {
    if (apcontinue == null) {
      apcontinue = '';
    }
    return fetch(callback, apcontinue);
  };

}).call(this);

/*
//@ sourceMappingURL=spider_moegirlwiki.map
*/
