// Generated by CoffeeScript 1.7.1
(function() {
  var child_process, express, nekoime, router;

  child_process = require('child_process');

  nekoime = require('../../nekoime');

  express = require("express");

  router = express.Router();

  router.get("/logo.png", function(req, res) {
    return res.sendfile("./lib/backends/sunpinyin/logo.png");
  });

  router.get("/config", function(req, res) {
    child_process.execFile('fcitx-configtool');
    return res.send(204);
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=route.map
