// Generated by CoffeeScript 1.7.1
(function() {
  var child_process, express, formidable, nekoime, pinyin, router;

  child_process = require('child_process');

  formidable = require('formidable');

  pinyin = require("pinyin");

  nekoime = require('../../nekoime');

  express = require("express");

  router = express.Router();

  router.get("/logo.png", function(req, res) {
    return res.sendfile("./lib/sources/googleplus/logo.png");
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=route.map
