// Generated by CoffeeScript 1.6.3
(function() {
  var pinyin;

  pinyin = require("pinyinjs");

  Server.registerTranscoder({
    name: 'pinyin'
  });

  Server.on('Transcoder.run', function(item) {
    return console.log(word);
  });

  module.exports = function(word) {
    return pinyin(word, {
      style: pinyin.STYLE_NORMAL
    });
  };

}).call(this);

/*
//@ sourceMappingURL=pinyin.map
*/
